// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkKyG_vB-g4tNwiI-RfDC5qkWMO9vyxVU',
    appId: '1:524469739670:web:e3e3becebba5a733c7a2b7',
    messagingSenderId: '524469739670',
    projectId: 'flutter-getx-auth',
    authDomain: 'flutter-getx-auth.firebaseapp.com',
    storageBucket: 'flutter-getx-auth.appspot.com',
    measurementId: 'G-ZRBX5L9TBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJt4Ro9sOvAaDCKKiq5Vzez_mFVSDMLI',
    appId: '1:524469739670:android:021d1fe43b324672c7a2b7',
    messagingSenderId: '524469739670',
    projectId: 'flutter-getx-auth',
    storageBucket: 'flutter-getx-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8iqgHOAQDfhfxME11T002HZV1JoYn8Ws',
    appId: '1:524469739670:ios:e80a15b50bdbc683c7a2b7',
    messagingSenderId: '524469739670',
    projectId: 'flutter-getx-auth',
    storageBucket: 'flutter-getx-auth.appspot.com',
    iosClientId: '524469739670-09p52na4jli010p00pmurcs0brmv6th2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppG',
  );
}
